//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ThaiPost.thailandpost.track {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Track and Trace ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class TrackandTraceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private PublicKeySoapHeader publicKeySoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestItemsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TrackandTraceService() {
            this.Url = global::ThaiPost.Properties.Settings.Default.ThaiPost_thailandpost_track_Track_x0020_and_x0020_Trace_x0020_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public PublicKeySoapHeader PublicKeySoapHeaderValue {
            get {
                return this.publicKeySoapHeaderValueField;
            }
            set {
                this.publicKeySoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetItemsCompletedEventHandler GetItemsCompleted;
        
        /// <remarks/>
        public event RequestItemsCompletedEventHandler RequestItemsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PublicKeySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItems", RequestNamespace="http://www.xmlforasp.net", ResponseNamespace="http://www.xmlforasp.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TrackItem GetItems(string user, string password, string lang, string Barcode) {
            object[] results = this.Invoke("GetItems", new object[] {
                        user,
                        password,
                        lang,
                        Barcode});
            return ((TrackItem)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsAsync(string user, string password, string lang, string Barcode) {
            this.GetItemsAsync(user, password, lang, Barcode, null);
        }
        
        /// <remarks/>
        public void GetItemsAsync(string user, string password, string lang, string Barcode, object userState) {
            if ((this.GetItemsOperationCompleted == null)) {
                this.GetItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsOperationCompleted);
            }
            this.InvokeAsync("GetItems", new object[] {
                        user,
                        password,
                        lang,
                        Barcode}, this.GetItemsOperationCompleted, userState);
        }
        
        private void OnGetItemsOperationCompleted(object arg) {
            if ((this.GetItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsCompleted(this, new GetItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PublicKeySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestItems", RequestNamespace="http://www.xmlforasp.net", ResponseNamespace="http://www.xmlforasp.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TrackRequest RequestItems(string user, string password, string lang, string[] Barcode) {
            object[] results = this.Invoke("RequestItems", new object[] {
                        user,
                        password,
                        lang,
                        Barcode});
            return ((TrackRequest)(results[0]));
        }
        
        /// <remarks/>
        public void RequestItemsAsync(string user, string password, string lang, string[] Barcode) {
            this.RequestItemsAsync(user, password, lang, Barcode, null);
        }
        
        /// <remarks/>
        public void RequestItemsAsync(string user, string password, string lang, string[] Barcode, object userState) {
            if ((this.RequestItemsOperationCompleted == null)) {
                this.RequestItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestItemsOperationCompleted);
            }
            this.InvokeAsync("RequestItems", new object[] {
                        user,
                        password,
                        lang,
                        Barcode}, this.RequestItemsOperationCompleted, userState);
        }
        
        private void OnRequestItemsOperationCompleted(object arg) {
            if ((this.RequestItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestItemsCompleted(this, new RequestItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class PublicKeySoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string publicXmlKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string PublicXmlKey {
            get {
                return this.publicXmlKeyField;
            }
            set {
                this.publicXmlKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xmlforasp.net")]
    public partial class RequestCount {
        
        private string trackDateField;
        
        private string trackStatusField;
        
        private string countNumberField;
        
        /// <remarks/>
        public string TrackDate {
            get {
                return this.trackDateField;
            }
            set {
                this.trackDateField = value;
            }
        }
        
        /// <remarks/>
        public string TrackStatus {
            get {
                return this.trackStatusField;
            }
            set {
                this.trackStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CountNumber {
            get {
                return this.countNumberField;
            }
            set {
                this.countNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xmlforasp.net")]
    public partial class ItemsRequest {
        
        private string statusResponseField;
        
        /// <remarks/>
        public string StatusResponse {
            get {
                return this.statusResponseField;
            }
            set {
                this.statusResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xmlforasp.net")]
    public partial class TrackRequest {
        
        private ItemsRequest itemsDataField;
        
        private RequestCount requestCountDataField;
        
        /// <remarks/>
        public ItemsRequest ItemsData {
            get {
                return this.itemsDataField;
            }
            set {
                this.itemsDataField = value;
            }
        }
        
        /// <remarks/>
        public RequestCount RequestCountData {
            get {
                return this.requestCountDataField;
            }
            set {
                this.requestCountDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xmlforasp.net")]
    public partial class TrackCount {
        
        private string trackDateField;
        
        private string trackStatusField;
        
        private string countNumberField;
        
        /// <remarks/>
        public string TrackDate {
            get {
                return this.trackDateField;
            }
            set {
                this.trackDateField = value;
            }
        }
        
        /// <remarks/>
        public string TrackStatus {
            get {
                return this.trackStatusField;
            }
            set {
                this.trackStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CountNumber {
            get {
                return this.countNumberField;
            }
            set {
                this.countNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xmlforasp.net")]
    public partial class Items {
        
        private string barcodeField;
        
        private string statusField;
        
        private string statusNameField;
        
        private string descriptionField;
        
        private string dateTimeField;
        
        private string signatureField;
        
        private string locationField;
        
        private string deliveryDateTimeField;
        
        private string postCodeField;
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryDateTime {
            get {
                return this.deliveryDateTimeField;
            }
            set {
                this.deliveryDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xmlforasp.net")]
    public partial class TrackItem {
        
        private Items[] itemsDataField;
        
        private TrackCount trackCountDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Items[] ItemsData {
            get {
                return this.itemsDataField;
            }
            set {
                this.itemsDataField = value;
            }
        }
        
        /// <remarks/>
        public TrackCount TrackCountData {
            get {
                return this.trackCountDataField;
            }
            set {
                this.trackCountDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetItemsCompletedEventHandler(object sender, GetItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TrackItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TrackItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void RequestItemsCompletedEventHandler(object sender, RequestItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TrackRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TrackRequest)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591